version: '3.7'

services:
    campaignapp:
        image: xrecruit/campaignapp:staging
        build:
            context: .
            dockerfile: Dockerfile.staging
        volumes: 
            - /var/log/nginx/recruitfrontend:/var/log/nginx
        ports:
            - "9999:80"
